apiVersion: v1
kind: Secret
metadata:
  name: homeplan-postgres
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: {{ printf "postgres://%s:%s@homeplan-postgres:5432/%s?sslmode=disable" (.Values.postgres.user | urlquery) (.Values.postgres.password | urlquery) (.Values.postgres.database | urlquery) | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.api.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.api.googleClientSecret | quote }}
